version: "3"

services: 
  app:
    build: 
      context: .
    ports: 
      - "8000:8000"
    volumes: 
      - ./app:/app
    command: >
      sh -c "sleep 1 &&
             python manage.py collectstatic --no-input --clear && 
             python manage.py runserver 0.0.0.0:8000"
    env_file: .env.localhost
    depends_on: 
      - db
  
  db:
    image: postgres:10-alpine
    ports: 
     - "5431:5431"
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
